### ISSUE TITLE
Error while building ./my-command.js

### ISSUE THREAD

**Issue by danielthall** [skpm/with-webview#21]
I just installed this package following the instructions on the Readme and when trying to run `npm run watch` I immediately get the following error:

```error Error while building ./my-command.js
./src/my-command.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /src/my-command.js: Package exports for '/node_modules/@babel/helper-compilation-targets' do not define a '.' subpath (While processing: "base$0")
    at applyExports (internal/modules/cjs/loader.js:485:15)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/node_modules/@babel/preset-env/lib/index.js:11:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)```

Anyone else running into this?

**Comment by danielthall** [comment]
This was solved by updating my node version. https://github.com/babel/babel/issues/10997
